version: "3.9"
services:
  mysql:
    platform: linux/x86_64
    image: percona:5.7
    ports:
      - "3390:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
      TZ: Asia/Jakarta
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
  #   depends_on:
  #     - mysql
    # entrypoint:
    #   [
    #     "/app/wait-for.sh",
    #     "postgres:5432",
    #     "--",
    #     "/app/start.sh"
    #   ]
    # command: [ "/app/main" ]