version: "3.9"
services:
  mysql:
    platform: linux/x86_64
    image: percona:5.7
    ports:
      - "3390:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Jakarta
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    environment:
      - DB_SOURCE=mysql://app:secret@tcp(mysql:3306)/app?timeout=2s&parseTime=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=app
      - DB_PASS=secret
      - DB_NAME=app
    depends_on:
      - mysql
    entrypoint: ["/app/wait-for.sh", "mysql:3306", "--timeout=60", "--", "/app/start.sh"]
    command: ["/app/main"]
