name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: percona:5.7
        ports:
          - "3390:3306"
        env:
          MYSQL_DATABASE: app
          MYSQL_USER: app
          MYSQL_PASSWORD: app
          MYSQL_ROOT_PASSWORD: app
          TZ: Asia/Jakarta
        # options: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Test
      run: make test
