name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop

    - name: Setup Mysql
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3390
        container port: 3390
        character set server: 'utf8mb4'
        collation server: 'utf8mb4_unicode_ci'
        mysql version: '5.7'
        mysql database: 'app'
        mysql user: 'app'
        mysql password: 'secret'

    - name: Check DB
      run: mysqlshow -h 127.0.0.1 -P 3390 -u app -psecret

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/migrate
        which migrate

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
